import keyImage from "@/assets/95505d4ee000f9810ff5b47d6c3efbc8f55c090d.png";

export const keysData = [
  {
    id: 1,
    make: "Mazda",
    model: "CX-5",
    year: "2021",
    title: "Smart Key Proximity",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 2,
    make: "Mazda",
    model: "Mazda3",
    year: "2020",
    title: "Keyless Entry Remote",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 3,
    make: "Mazda",
    model: "CX-9",
    year: "2019",
    title: "Advanced Smart Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 4,
    make: "Toyota",
    model: "Camry",
    year: "2022",
    title: "Smart Key System",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 5,
    make: "Toyota",
    model: "RAV4",
    year: "2021",
    title: "Proximity Smart Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 6,
    make: "Honda",
    model: "Accord",
    year: "2020",
    title: "Smart Entry Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 7,
    make: "Honda",
    model: "CR-V",
    year: "2021",
    title: "Keyless Access Remote",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 8,
    make: "Nissan",
    model: "Altima",
    year: "2019",
    title: "Intelligent Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 9,
    make: "Nissan",
    model: "Rogue",
    year: "2020",
    title: "Smart Key Fob",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 10,
    make: "Hyundai",
    model: "Sonata",
    year: "2021",
    title: "Smart Key Remote",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 11,
    make: "Hyundai",
    model: "Tucson",
    year: "2020",
    title: "Proximity Key Fob",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 12,
    make: "Kia",
    model: "Optima",
    year: "2019",
    title: "Smart Key Entry",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 13,
    make: "Kia",
    model: "Sportage",
    year: "2021",
    title: "Keyless Smart Remote",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 14,
    make: "Ford",
    model: "Fusion",
    year: "2020",
    title: "Intelligent Access Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 15,
    make: "Ford",
    model: "Escape",
    year: "2021",
    title: "Smart Proximity Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 16,
    make: "Chevrolet",
    model: "Malibu",
    year: "2019",
    title: "Remote Keyless Entry",
    market: "US",
    type: "Remote Key",
    image: keyImage,
  },
  {
    id: 17,
    make: "Chevrolet",
    model: "Equinox",
    year: "2020",
    title: "Smart Key Fob",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 18,
    make: "Subaru",
    model: "Outback",
    year: "2021",
    title: "Keyless Access Fob",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 19,
    make: "Subaru",
    model: "Forester",
    year: "2020",
    title: "Proximity Smart Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 20,
    make: "Volkswagen",
    model: "Jetta",
    year: "2019",
    title: "Smart Key Remote",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 21,
    make: "Volkswagen",
    model: "Tiguan",
    year: "2021",
    title: "Keyless Entry System",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 22,
    make: "BMW",
    model: "3 Series",
    year: "2020",
    title: "Comfort Access Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 23,
    make: "Mercedes-Benz",
    model: "C-Class",
    year: "2021",
    title: "Keyless Go Fob",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 24,
    make: "Audi",
    model: "A4",
    year: "2020",
    title: "Advanced Key System",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
  {
    id: 25,
    make: "Lexus",
    model: "ES",
    year: "2021",
    title: "Smart Access Key",
    market: "US",
    type: "Smart Key",
    image: keyImage,
  },
];
